nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.0.2.cjs

supportedArchitectures:
  os:
    - 'current'
    - 'darwin'
    - 'linux'
    - 'win32'
  cpu:
    - 'current'
    - 'x64'
    - 'arm64'
